// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxayzunpqoqoyadpcpuh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4YXl6dW5wcW9xb3lhZHBjcHVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2ODc1MTksImV4cCI6MjA3MzI2MzUxOX0.ZXKeqo82SsKxMxlzlgW9FQwX_T0B1URkKVkODvlzuzc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});